### Health Check
GET http://localhost:8080/
Accept: application/json

### Ambil semua kategori
GET http://localhost:8080/categories
Accept: application/json

### Tambah kategori baru
POST http://localhost:8080/categories
Content-Type: application/json
Accept: application/json

{
  "name": "Minuman 2",
  "description": "Kategori untuk semua jenis minuman"
}

### Ambil detail kategori berdasarkan ID
GET http://localhost:8080/categories/1
Accept: application/json

### Update kategori berdasarkan ID
PUT http://localhost:8080/categories/2
Content-Type: application/json
Accept: application/json

{
  "name": "Minuman Segar",
  "description": "Kategori untuk minuman dingin dan segar"
}

### Hapus kategori berdasarkan ID
DELETE http://localhost:8080/categories/3
Accept: application/json


///////////PRODUK///////////

### Ambil semua produk
GET http://localhost:8080/products
Accept: application/json

### Tambah produk baru
POST http://localhost:8080/products
Content-Type: application/json
Accept: application/json

{
  "name": "Nasi Goreng",
  "price": 20000,
  "stock": 50,
  "category_id": 1
}

### Ambil detail produk berdasarkan ID
GET http://localhost:8080/products/1
Accept: application/json

### Update produk berdasarkan ID
PUT http://localhost:8080/products/1
Content-Type: application/json
Accept: application/json

{
  "name": "Nasi Goreng Spesial",
  "price": 25000,
  "stock": 40,
  "category_id": 1
}

### Hapus produk berdasarkan ID
DELETE http://localhost:8080/products/2
Accept: application/json